In [1]:
# import debugger
import pdb

import re

# selenium
import selenium
import pandas as pd
from selenium import webdriver


# BeautifulSoup
from bs4 import BeautifulSoup
import requests

# add time
import time

#to send keys from keyboard
from selenium.webdriver.common.keys import Keys

from selenium.common.exceptions import NoSuchElementException

from selenium.webdriver.common.action_chains import ActionChains

from selenium.webdriver.common.alert import Alert

In [2]:
def open_url(url):
    """function to open the entered url in browser"""
    global driver
    # first, connect to the webdriver
    driver=webdriver.Chrome(r'C:\Users\admin\Downloads\chromedriver_win32\chromedriver.exe')
    driver.get(url)

## 1. Scrape the details of most viewed videos on YouTube from Wikipedia:
### Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
#### You need to find following details:
#### A) Rank
#### B) Name
#### C) Artist
#### D) Upload date
#### E) Views

In [8]:
Url ='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'

In [9]:
open_url(Url)

# get webelements for all 30 rows
top30_rows_wbe=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//following::tbody")
# get webelement for table with top 30 YT videos list
# store all text in a list
for i in top30_rows_wbe:
    temp_text=i.text
    break # exit after first iteration
    
sep_rows=temp_text.split('\n')

rank=[]
rank.clear()
vid_name=[]
vid_name.clear()
artist=[]
artist.clear()
views=[]
views.clear()
date=[]
date.clear()

for i in sep_rows:
    
    rank.append(i.split('.')[0])
    
    vid_name.append(i.split('[')[0].split('.')[-1].strip())
    
    artist.append(re.split('\d+',i.split(']')[1])[0])
    
    views.append(str(re.compile('\d+').findall(i.split(']')[1])[0])+'.'+str(re.compile('\d+').findall(i.split(']')[1])[1]))
    
    date.append(str(re.compile('[a-zA-Z]+\s+\d{2}').findall(i.split('.')[2]))+','+str(re.compile('\d{4}').findall(i.split('.')[2])))

In [10]:
top30_vid=pd.DataFrame({})
top30_vid['Rank']=rank
top30_vid['Name']=vid_name
top30_vid['Artist']=artist
top30_vid['Views (in billions)']=views
top30_vid['Release Date']=date

In [11]:
top30_vid

,Rank,Name,Artist,Views (in billions),Release Date
0,1,"""Baby Shark Dance""",Pinkfong Kids' Songs & Stories,8.96,"['June 17'],['2016']"
1,2,"""Despacito""",Luis Fonsi,7.44,"['January 12'],['2017']"
2,3,"""Johny Johny Yes Papa""",LooLoo Kids,5.55,"[],['2016']"
3,4,"""Shape of You""",Ed Sheeran,5.38,"['January 30'],['2017']"
4,5,"""See You Again""",Wiz Khalifa,5.18,"[],['2015']"
5,6,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.44,"['January 31'],['2012']"
6,7,"""Bath Song""",Cocomelon – Nursery Rhymes,4.31,"[],['2018']"
7,8,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,4.26,"['February 27'],['2018']"
8,9,"""Uptown Funk""",Mark Ronson,4.23,"['November 19'],['2014']"
9,10,"""Gangnam Style""",Psy,4.12,"['July 15'],['2012']"
10,11,"""Phonics Song with Two Words""",ChuChu TV,3.99,"[],['2014']"
11,12,"""Sugar""",Maroon,5.3,"['January 14'],['2015']"
12,13,"""Dame Tu Cosita""",El Chombo,3.46,"[],['2018']"
13,14,"""Sorry""",Justin Bieber,3.45,"['October 22'],['2015']"
14,15,"""Roar""",Katy Perry,3.39,"[],['2013']"
15,16,"""Counting Stars""",OneRepublic,3.34,"['May 31'],['2013']"
16,17,"""Thinking Out Loud""",Ed Sheeran,3.29,"[],['2014']"
17,18,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,3.15,"['May 24'],['2018']"
18,19,"""Dark Horse""",Katy Perry,3.10,"['February 20'],['2014']"
19,20,"""Faded""",Alan Walker,3.10,"[],['2015']"
20,21,"""Shake It Off""",Taylor Swift,3.07,"['August 18'],['2014']"
21,22,"""Girls Like You""",Maroon,5.3,"['May 31'],['2018']"
22,23,"""Lean On""",Major Lazer,3.06,"['March 22'],['2015']"
23,24,"""Bailando""",Enrique Iglesias,3.06,"['April 11'],['2014']"
24,25,"""Let Her Go""",Passenger,3.03,"['July 25'],['2012']"
25,26,"""Mi Gente""",J Balvin,2.94,"['June 29'],['2017']"
26,27,"""Perfect""",Ed Sheeran,2.90,"[],['2017']"
27,28,"""Waka Waka (This Time for Africa)""",Shakira,2.88,"[],['2010']"
28,29,"""Axel F""",Crazy Frog,2.88,"['June 16'],['2009']"
29,30,"""Hello""",Adele,2.85,"['October 22'],['2015']"

## 2. Scrape the details team India’s international fixtures from bcci.tv.
### Url = https://www.bcci.tv/.
#### You need to find following details:
#### A) Match title (I.e. 1st ODI)
#### B) Series
#### C) Place
#### D) Date
#### E) Time
#### Note: - From bcci.tv home page you have reach to the international fixture page through code

In [12]:
open_url('https://www.bcci.tv')

time.sleep(5)

# click on "International" button to expand it
driver.find_element_by_xpath("//li[@data-nav-index='0']").click()

# click on 'Fixtures'
driver.find_element_by_xpath("//li[@data-nav-index='0']//following::a[@href='/international/fixtures']").click()

time.sleep(3)

# store webelements for all series names
series_wbe=driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span")

fixture_frame_text=[]

for i in series_wbe:
    fixture_frame_text.append(i.text)
    
fixture_name=[]
fixture_name.clear()
fixture_type=[]
fixture_type.clear()

time.sleep(3)

for i in range(len(fixture_frame_text)):
    if i%2!=0:
        fixture_name.append(fixture_frame_text[i])
    else:
        fixture_type.append(fixture_frame_text[i])

# get webelment for match title
title_wbe=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']")

title=[]
title.clear()
loc=[]
loc.clear()

for i in title_wbe:
    title.append(i.text.split('\n')[0])
    loc.append(i.text.split('\n')[1])
    
#get webelement for date and time
try:
    date_wbe=driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']")
except:
    pass

date=[]
date.clear()
time=[]
time.clear()

for i in date_wbe:
#     pdb.set_trace()
    date.append(str(i.text.split('\n')[0])+str('-')+str(i.text.split('\n')[1]+str('th')+str(i.text.split('\n')[2])))
    time.append(i.text.split('\n')[3])

In [13]:
ind_fixture=pd.DataFrame({})
ind_fixture['Tournament']=fixture_name
ind_fixture['Fixture']=fixture_type
ind_fixture['Match']=title
ind_fixture['Venue']=loc
ind_fixture['Date']=date
ind_fixture['Time']=time

In [14]:
ind_fixture

,Tournament,Fixture,Match,Venue,Date,Time
0,SRI LANKA V INDIA 2021,ODI,1st ODI,"R Premadasa Stadium, Colombo",Sunday-18thJULY,15:00 IST
1,SRI LANKA V INDIA 2021,ODI,2nd ODI,"R Premadasa Stadium, Colombo",Tuesday-20thJULY,15:00 IST
2,SRI LANKA V INDIA 2021,ODI,3rd ODI,"R Premadasa Stadium, Colombo",Friday-23thJULY,15:00 IST
3,SRI LANKA V INDIA 2021,T20I,1st T20I,"R Premadasa Stadium, Colombo",Sunday-25thJULY,20:00 IST
4,SRI LANKA V INDIA 2021,T20I,2nd T20I,"R Premadasa Stadium, Colombo",Tuesday-27thJULY,20:00 IST
5,SRI LANKA V INDIA 2021,T20I,3rd T20I,"R Premadasa Stadium, Colombo",Thursday-29thJULY,20:00 IST
6,ENGLAND V INDIA 2021,TEST,1st Test,"Trent Bridge, Nottingham",Wednesday-04thAUGUST,15:30 IST
7,ENGLAND V INDIA 2021,TEST,2nd Test,"Lord's, London",Thursday-12thAUGUST,15:30 IST
8,ENGLAND V INDIA 2021,TEST,3rd Test,"Headingley, Leeds",Wednesday-25thAUGUST,15:30 IST
9,ENGLAND V INDIA 2021,TEST,4th Test,"The Oval, London",Thursday-02thSEPTEMBER,15:30 IST
10,ENGLAND V INDIA 2021,TEST,5th Test,"Old Trafford, Manchester",Friday-10thSEPTEMBER,15:30 IST

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
- You need to find following details:
#### A) Name
#### B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [16]:
Url='https://www.guru99.com'
open_url(Url)

# click on 'Selenium' on main page
driver.find_element_by_xpath("//a[text()='Selenium']").click()

# time.sleep(5)
# click on Selenium Exception page
driver.find_element_by_xpath("//td[contains(text(),'Selenium Exception')]//preceding-sibling::td[@class='responsivetable']").click()

# get webelement for table with data
table_wbe=driver.find_element_by_xpath("//table[@class='table table-striped']")

table_data = table_wbe.text

row_data = table_data.split('\n')

name=[]
descr=[]

for i in row_data[1:]:
    name.append(i.split(' ')[0])
    descr.append(' '.join(i.split(' ')[1:]))

In [17]:
guru99_tut=pd.DataFrame({})
guru99_tut['Exception']=name
guru99_tut['Description']=descr

In [18]:
guru99_tut

,Exception,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

## 4. Scrape the details of State-wise GDP of India from statisticstime.com.
 Url = http://statisticstimes.com/
You have to find following details:
- A) Rank
- B) State
- C) GSDP at current price (19-20)
- D) GSDP at current price (18-19)
- E) Share(18-19)
- F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [ ]:
Url ='http://statisticstimes.com/'

open_url(Url)

# main_window = driver.current_window_handle

a = ActionChains(driver)

# get webelement for 'Economy' button
eco_wbe = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
# keep mouse on above webelement to get drop down list
a.move_to_element(eco_wbe).perform()
#click on 'India' from drop down
driver.find_element_by_xpath("//a[@href='economy/india-statistics.php']").click() #//*[@id="top"]/div[2]/div[2]/div/a[3]


driver.find_element_by_xpath("//div[@id='ad_position_box']/div[@class='mys-wrapper']/div[@id='dismiss-button']").click()

# click on Statwise GDP
driver.find_element_by_xpath("//div[contains(@style,'seashell')]/ul/li[1]").click()
#get webelements
rank_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[1]")
state_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[2]")
gsdp_19_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[3]")
gsdp_18_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[4]")
share_18_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[5]")
gdp_wbe = driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr[@role='row']/td[6]")
# get text from above webelements
rank=[]
state=[]
gsdp_19=[]
gsdp_18=[]
share_18=[]
gdp=[]
for i in rank_wbe:
    rank.append(i.text)
for i in state_wbe:
    state.append(i.text)
for i in gsdp_19_wbe:
    gsdp_19.append(i.text)
for i in gsdp_18_wbe:
    gsdp_18.append(i.text)
for i in share_18_wbe:
    share_18.append(i.text)
for i in gdp_wbe:
    gdp.append(i.text)

In [ ]:
statewise_gdp = pd.DataFrame({})
statewise_gdp['Rank']=rank
statewise_gdp['State']=state
statewise_gdp['GSDP at current price (19-20)']=gsdp_19
statewise_gdp['GSDP at current price (18-19)']=gsdp_18
statewise_gdp['Share(18-19)']=share_18
statewise_gdp['GDP in billion $']=gdp

In [ ]:
statewise_gdp

## 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:
- A) Repository title
- B) Repository description
- C) Contributors count
- D) Language used

In [ ]:
Url = 'https://github.com/'
open_url(Url)

time.sleep(3)

# get webelement for "Explore" button and hover over it
# a = ActionChains(driver)

explore_wbe = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore_wbe.click()
# a.move_to_element(explore_wbe).perform()

# click on "trending"
driver.find_element_by_xpath("//li[@class='edge-item-fix']//following::a[@href='/trending']").click()

time.sleep(3)

# below block gets repo and user name
user_names = []
user_names.clear()

repo_names = []
repo_names.clear()

repo_wbe = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

for i in repo_wbe:
    user_names.append(i.text.split('/')[0])
    repo_names.append(i.text.split('/')[1])
    
# below block finds languauges used
time.sleep(3)
# get webelement for language row
lang_wbe = driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']")

lang = []
lang.clear()

for i in lang_wbe:
    if i.text.split(' ')[0].isalpha() == True:
        lang.append(i.text.split(' ')[0])
    else:
        lang.append('---')
        
# below block will fetch contributor's count
contri_wbe = driver.find_elements_by_xpath("//span[@class='d-inline-block mr-3']")

numb_contri = []
numb_contri.clear()

for i in contri_wbe:
    numb_contri.append(len(i.find_elements_by_tag_name("a")))
#     pdb.set_trace()

In [ ]:
github_repo = pd.DataFrame({})
github_repo['Username'] = user_names
github_repo['Repository'] = repo_names
github_repo['Language'] = lang
github_repo['Number of contributors'] = numb_contri

In [ ]:
github_repo

## 6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/

You have to find the following details:
- A) Song name
- B) Artist name
- C) Last week rank
- D) Peak rank
- E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
Url ='https://www.billboard.com/'
# open_url(Url)

driver=webdriver.Chrome(r'C:\Users\admin\Downloads\chromedriver_win32\chromedriver.exe')

#enter the url
driver.get(Url)

driver.set_page_load_timeout(300)

# click on "Hot 100" button
driver.find_element_by_xpath("//li[@class='header__subnav__item']//following::a[@href='/charts/hot-100' and @data-track='navigation']").click()


# get chart-element wbe
chart_element_wbe_1 = driver.find_elements_by_xpath("//span[@class='chart-element__information']")
chart_element_wbe_2 = driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']")

song_names = []
song_names.clear()

artist_names = []
artist_names.clear()

lwk_rank = []
lwk_rank.clear()

peak_rank = []
peak_rank.clear()

wks_oc = []
wks_oc.clear()

for i in chart_element_wbe_1:
    song_names.append(i.text.split('\n')[0])
    artist_names.append(i.text.split('\n')[1])


for i in chart_element_wbe_2:
    lwk_rank.append(i.text.split('\n')[0])
    peak_rank.append(i.text.split('\n')[1])
    wks_oc.append(i.text.split('\n')[2])
#     pdb.set_trace()

AttributeError: 'NoneType' object has no attribute 'split'

In [22]:
top100_billboard = pd.DataFrame({})
top100_billboard['Song'] = song_names
top100_billboard['Artist'] = artist_names
top100_billboard['Last Week Rank'] = lwk_rank
top100_billboard['Peak Rank'] = peak_rank
top100_billboard['Weeks on Chart'] = wks_oc

In [23]:
top100_billboard

,Song,Artist,Last Week Rank,Peak Rank,Weeks on Chart
0,Butter,BTS,1,1,7
1,Good 4 U,Olivia Rodrigo,2,1,8
2,Levitating,Dua Lipa Featuring DaBaby,4,2,40
3,Kiss Me More,Doja Cat Featuring SZA,3,3,13
4,Montero (Call Me By Your Name),Lil Nas X,8,1,15
...,...,...,...,...,...
95,All I Know So Far,P!nk,-,74,4
96,What's Next,Drake,-,1,16
97,Enough For You,Olivia Rodrigo,-,14,6
98,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
99,Tell Em,Cochise & $NOT,-,64,4

## 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/

You have to find the following details:
- A) Name
- B) Designation
- C) Company
- D) Skills they hire for
- E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [ ]:
driver = webdriver.Chrome(r'C:\Users\admin\Downloads\chromedriver_win32\chromedriver.exe')
# open url
driver.get('https://www.naukri.com/')
# give time to load webpage
driver.set_page_load_timeout(60)
# store main page window handle
main_window = driver.current_window_handle
# remove 2nd window which will be a ad popup
driver.switch_to.window(driver.window_handles[1])
driver.close()
driver.switch_to.window(main_window)
# close the alert
try:
    a = Alert(driver)
    a.dismiss()
except:
    pass
# click on "Recruiters"
driver.find_element_by_xpath("//ul[@class='midSec menu']//following::a[@title='Search Recruiters']").click()

# switch to new tab
driver.switch_to.window(driver.window_handles[1])
# get webelement for search bar
search_wbe = driver.find_element_by_xpath("//div[@class='inpWrap']//following::input[@placeholder='Skills, Designations, Companies']")
# search keyword
search_wbe.send_keys("Data Scientist",Keys.ENTER)
# get recruiters info webelements
vcard_wbe = driver.find_elements_by_xpath("//div[@class='vcard']")
skills_wbe = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
# get text from webelements
rec_names = []
rec_names.clear()
rec_roles = []
rec_roles.clear()
rec_companies = []
rec_companies.clear()
rec_locations = []
rec_locations.clear()
skills = []
skills.clear()
# iterating over recruiters info
for i in vcard_wbe:
#     pdb.set_trace()
    if len(i.text.split('\n')) == 4: # if location info is avaialble
        rec_names.append(i.text.split('\n')[0])
        rec_roles.append(i.text.split('\n')[1])
        rec_companies.append(i.text.split('\n')[2])
        rec_locations.append(i.text.split('\n')[3])
    elif len(i.text.split('\n')) == 3: # if location info is missing
        rec_names.append(i.text.split('\n')[0])
        rec_roles.append(i.text.split('\n')[1])
        rec_companies.append(i.text.split('\n')[2])
        rec_locations.append('---')
# iterating over skills sought by recruiters
for i in skills_wbe:
    skills.append(i.text)

In [ ]:
naukri_recr = pd.DataFrame({})
naukri_recr['Name of Recruiter'] = rec_names
naukri_recr['Role'] = rec_roles
naukri_recr['Company'] = rec_companies
naukri_recr['Location'] = rec_locations
naukri_recr['Skills looking for'] = skills

In [ ]:
naukri_recr

## 8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:
- A) Book name
- B) Author name
- C) Volumes sold
- D) Publisher
- E) Genre

In [31]:
Url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'
open_url(Url)
# get web elements
rank_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[1]")
bname_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
auth_name_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
vols_sold_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
publisher_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
genre_wbe = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
time.sleep(3)
rank=[]
bname=[]
auth_name=[]
vols_sold=[]
publisher=[]
genre=[]
for i in rank_wbe:
    rank.append(i.text)
for i in bname_wbe:
    bname.append(i.text)
for i in auth_name_wbe:
    auth_name.append(i.text)
for i in vols_sold_wbe:
    vols_sold.append(i.text)
for i in publisher_wbe:
    publisher.append(i.text)
for i in genre_wbe:
    genre.append(i.text)

In [32]:
best_novels = pd.DataFrame({})
best_novels['Rank'] = rank
best_novels['Title'] = bname
best_novels['Author'] = auth_name
best_novels['Volumes Sold'] = vols_sold
best_novels['Publisher'] = publisher
best_novels['Genre'] = genre

In [33]:
best_novels

,Rank,Title,Author,Volumes Sold,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## 9. Scrape the details most watched tv series of all time from imdb.com.
 
 Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:
- A) Name
- B) Year span
- C) Genre
- D) Run time
- E) Ratings
- F) Votes

In [25]:
Url='https://www.imdb.com/list/ls095964455/'
open_url(Url)
#get webelements
title_wbe = driver.find_elements_by_xpath("//div[@class='lister-item-content']/h3/a")
yr_span_wbe = driver.find_elements_by_xpath("//div[@class='lister-item-content']/h3/span[2]")
genre_wbe = driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[@class='text-muted text-small']/span[@class='genre']")
run_time_wbe = driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[@class='text-muted text-small']/span[@class='runtime']")
rating_wbe = driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[@class='ipl-rating-star__rating']")
votes_wbe = driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[@class='text-muted text-small']/span[@name='nv']")

title=[]
yr_span=[]
genre=[]
run_time=[]
rating=[]
votes=[]

for i in title_wbe:
    title.append(i.text)
for i in yr_span_wbe:
    yr_span.append(i.text)
for i in genre_wbe:
    genre.append(i.text)
for i in run_time_wbe:
    run_time.append(i.text)
for i in rating_wbe:
    rating.append(i.text)
for i in votes_wbe:
    votes.append(i.text)

In [26]:
imdb_webseries = pd.DataFrame({})
imdb_webseries['Title'] = title
imdb_webseries['Year Span'] = yr_span
imdb_webseries['Genre'] = genre
imdb_webseries['Run Time'] = run_time
imdb_webseries['Rating'] = rating
imdb_webseries['Votes'] = votes

In [27]:
imdb_webseries

,Title,Year Span,Genre,Run Time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,835,393"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"874,161"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"879,319"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"264,212"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"225,709"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,790"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,397"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"169,584"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,120"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"193,351"

## 10. Details of Datasets from UCI machine learning repositories.
 
 Url = https://archive.ics.uci.edu/
 
 You have to find the following details:
- A) Dataset name
- B) Data type
- C) Task
- D) Attribute type
- E) No of instances
- F) No of attribute
- G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [28]:
Url ='https://archive.ics.uci.edu/'
open_url(Url)
#click on "view all repositories"
driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a').click()
# get all repositories
name_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[1]/table/tbody/tr/td[2]/p[@class='normal']/b/a")
dtypes_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[2]/p[@class='normal']")
task_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[3]/p[@class='normal']")
attr_types_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[4]/p[@class='normal']")
instances_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[5]/p[@class='normal']")
no_of_attr_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[6]/p[@class='normal']") 
yrs_wbe = driver.find_elements_by_xpath("//table[@border='1' and @cellpadding='5']/tbody/tr/td[7]/p[@class='normal']")
# get text from above webelements
repo_name=[]
dtypes=[]
task=[]
attr_types=[]
instances=[]
no_of_attr=[]
yrs=[]
for i in name_wbe:
    repo_name.append(i.text)
for i in dtypes_wbe:
    dtypes.append(i.text)
for i in task_wbe:
    task.append(i.text)
for i in attr_types_wbe:
    attr_types.append(i.text)
for i in instances_wbe:
    instances.append(i.text)
for i in no_of_attr_wbe:
    no_of_attr.append(i.text)
for i in yrs_wbe:
    yrs.append(i.text)

In [29]:
repositories = pd.DataFrame({})
repositories['Title']=repo_name
repositories['Data Types']=dtypes
repositories['Default Task']=task
repositories['Attribute Types']=attr_types
repositories['Instances']=instances
repositories['Attributes']=no_of_attr
repositories['Year']=yrs

In [30]:
repositories

,Title,Data Types,Default Task,Attribute Types,Instances,Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021